name: Release

on: [workflow_dispatch]

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
         zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-x86_64-linux-musl.xz 
         zig build -Doptimize=ReleaseFast -Dtarget=aarch64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-aarch64-linux-musl.xz 
         zig build -Doptimize=ReleaseFast -Dtarget=riscv64-linux-musl
         xz -zc zig-out/bin/droidux > droidux-riscv64-linux-musl.xz 

      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Development binary releases
          draft: false
          prerelease: false
          files: |
            droidux-x86_64-linux-musl.xz
            droidux-aarch64-linux-musl.xz
            droidux-riscv64-linux-musl.xz
